# -*- coding: utf-8 -*-
"""Instruction Fine-tuning  Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTCFpYUc3BSAMTxFqx8JfXiwgRqNiaXU

# ***IMPORTING***
"""

!pip install transformers accelerate datasets peft bitsandbytes evaluate

"""# ***Libraries***"""

import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

"""# ***DATASET***"""

from datasets import load_dataset

ds = load_dataset("alespalla/chatbot_instruction_prompts")

train_ds = ds["train"].shuffle(seed=42).select(range(10000))   # first 10k examples
test_ds = ds["test"].shuffle(seed=42).select(range(2000))      # first 2k examples

def format_example(e):
    return {
        "text": f"### Instruction:\n{e['prompt']}\n\n### Response:\n{e['response']}"
    }

train_ds = train_ds.map(format_example)
test_ds = test_ds.map(format_example)

print(train_ds[0])

"""# ***Tokenizer***"""

MODEL_NAME = "gpt2"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token # A: [101, 102, 2] , B: [101, 2,     2] --> 2 is <end> token to match the len
tokenizer.padding_side = "right"

"""# ***Load Model with 8-bit + LoRA Prep***"""

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    load_in_8bit=True,
    device_map="auto",
    torch_dtype=torch.float16
)

model = prepare_model_for_kbit_training(model)

"""# ***Apply LoRA Configuration***"""

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["c_attn"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

"""# ***Tokenization***"""

def tokenize_fn(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=256  # shorter for faster training
    )

# Tokenize the subset datasets
tokenized_train = train_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=train_ds.column_names  # remove only columns in subset
)

tokenized_test = test_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=test_ds.column_names
)

"""# ***Data Collator***"""

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

"""# ***evaluate***"""

import evaluate
import numpy as np

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

"""# ***Training Arguments***"""

training_args = TrainingArguments(
    output_dir="/content/support-bot-gpt2",
    num_train_epochs=1,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    fp16=True,
    save_steps=1000,
    logging_steps=50,
    eval_steps=1000,
    save_total_limit=2,
    load_best_model_at_end=False,
    report_to="none"
)

"""# ***Trainer Setup***"""

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,  # use tokenized subset
    eval_dataset=tokenized_test,    # use tokenized subset
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

"""# ***SAVING***"""

OUTPUT_DIR = "/content/support-bot-gpt2"

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training complete! Model saved to:", OUTPUT_DIR)

from google.colab import drive
drive.mount('/content/drive')

"""# ***Inference***"""

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load your fine-tuned model
OUTPUT_DIR = "/content/support-bot-gpt2"  # Folder where your model was saved

print("📥 Loading fine-tuned model for inference...")
tokenizer = AutoTokenizer.from_pretrained(OUTPUT_DIR)
model = AutoModelForCausalLM.from_pretrained(OUTPUT_DIR, device_map="auto", torch_dtype=torch.float16)
model.eval()

# Function for generating a response
def generate_response(prompt, max_length=200, temperature=0.7, top_p=0.9):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        output_ids = model.generate(
          **inputs,
          max_length=200,
          temperature=0.8,  # slightly higher randomness
          top_p=0.95,       # nucleus sampling
          do_sample=True,
          pad_token_id=tokenizer.eos_token_id,
          repetition_penalty=1.2  # discourages repetition
      )

    response = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    # Remove prompt from output
    return response[len(prompt):].strip()

# Example usage
prompt = "Answer this customer support question professionally and helpfully:\nHow do I return an item?"
response = generate_response(prompt)
print("🟢 Response:\n", response)

